#!/usr/bin/env escript

test(N) ->
  skewbinheap_eqc:test_min(N) and
  skewbinheap_eqc:test_sort(N) and
  skewbinheap_eqc:test_merge(N).

main([String]) ->
  N = try
    list_to_integer(String)
  catch
    _:_ -> usage()
  end,

  compile:file(skewbinheap),
  compile:file(skewbinheap_eqc),

  test(N);
main(_) -> main(["100"]).

usage() ->
  io:format("usage: test [iterations]\n"),
  halt(1).
